package sourcemap

import (
	"errors"
	"fmt"
	"go/token"
	"strings"

	unifiederrors "infomunge/internal/errors"
)

// Map tracks generated byte offsets back to the original source.
type Map struct {
	source     string
	generated  string
	positions  []int
	baseOffset int
}

// New constructs a map from generated output back to the original source.
func New(source, generated string, positions []int) Map {
	cloned := clonePositions(positions)
	if len(generated) > 0 && len(cloned) == 0 {
		cloned = IdentityPositions(len(generated))
	}
	return Map{
		source:    source,
		generated: generated,
		positions: cloned,
	}
}

// Identity returns an identity map over source.
func Identity(source string) Map {
	return New(source, source, IdentityPositions(len(source)))
}

// Generated returns the generated expression text.
func (m Map) Generated() string {
	return m.generated
}

// Positions returns a copy of the generated-to-source positions.
func (m Map) Positions() []int {
	return clonePositions(m.positions)
}

// WithBaseOffset anchors the source map within a larger source string.
func (m Map) WithBaseOffset(offset int) Map {
	m.baseOffset = offset
	return m
}

// ShiftBaseOffset shifts the anchor within the larger source string.
func (m Map) ShiftBaseOffset(delta int) Map {
	m.baseOffset += delta
	return m
}

// Compose remaps a local generated-to-input mapping into the original source.
func (m Map) Compose(generated string, local []int) Map {
	return New(m.source, generated, ComposePositions(m.positions, local)).WithBaseOffset(m.baseOffset)
}

// SliceSource creates a map for a source subrange within the original source.
func (m Map) SliceSource(start, end int) Map {
	if start < 0 {
		start = 0
	}
	if end < start {
		end = start
	}
	if end > len(m.source) {
		end = len(m.source)
	}
	positions := make([]int, end-start)
	for i := range positions {
		positions[i] = start + i
	}
	return New(m.source, m.source[start:end], positions).WithBaseOffset(m.baseOffset)
}

// SliceGenerated narrows the generated span while preserving original positions.
func (m Map) SliceGenerated(start, end int) Map {
	if start < 0 {
		start = 0
	}
	if end < start {
		end = start
	}
	if end > len(m.generated) {
		end = len(m.generated)
	}
	positions := clonePositions(m.positions[start:end])
	return New(m.source, m.generated[start:end], positions).WithBaseOffset(m.baseOffset)
}

// RewriteGenerated swaps the generated text while keeping source positions.
func (m Map) RewriteGenerated(generated string, positions []int) Map {
	return New(m.source, generated, positions).WithBaseOffset(m.baseOffset)
}

// RemapGeneratedOffset converts a generated offset to an absolute source offset.
func (m Map) RemapGeneratedOffset(offset int) int {
	if len(m.positions) == 0 {
		return clampOffset(m.baseOffset, len(m.source))
	}
	idx := ClampIndex(offset, len(m.positions))
	return clampOffset(m.positions[idx]+m.baseOffset, len(m.source))
}

// PositionForGeneratedOffset returns the original source position for a generated offset.
func (m Map) PositionForGeneratedOffset(offset int) token.Position {
	return unifiederrors.PositionFromOffset(m.source, m.RemapGeneratedOffset(offset), "")
}

// FormatParseError converts a parser error to original-source coordinates when possible.
func (m Map) FormatParseError(err error) error {
	if len(m.positions) == 0 {
		return err
	}

	line, col, ok := parseLineColPrefix(err.Error())
	if !ok {
		return err
	}

	offset := generatedLineColOffset(m.generated, line, col)
	pos := m.PositionForGeneratedOffset(offset)
	message := stripLineColPrefix(err.Error())
	return fmt.Errorf("%d:%d: %s", pos.Line, pos.Column, message)
}

// FormatEvalError converts evaluator positional errors back to original-source coordinates.
func (m Map) FormatEvalError(err error) error {
	if unifiedErr, ok := err.(*unifiederrors.Error); ok && unifiedErr.Position != nil {
		return fmt.Errorf("%s:%d:%d: %s", unifiedErr.Position.Filename, unifiedErr.Position.Line, unifiedErr.Position.Column, unifiedErr.Message)
	}

	var pe interface{ Pos() token.Pos }
	if errors.As(err, &pe) {
		pos := m.PositionForGeneratedOffset(int(pe.Pos()) - 1)
		return fmt.Errorf("%d:%d: %s", pos.Line, pos.Column, err.Error())
	}

	return err
}

// AttachLineContext adds a line preview and absolute position when absent.
func (m Map) AttachLineContext(err error, generatedOffset int, line string) error {
	if err == nil {
		return nil
	}

	unifiedErr, ok := err.(*unifiederrors.Error)
	if !ok || unifiedErr.Position != nil {
		return err
	}

	lineText := strings.TrimSpace(line)
	if lineText == "" {
		lineText = strings.TrimSpace(unifiederrors.LineTextAtOffset(m.source, m.RemapGeneratedOffset(generatedOffset)))
	}
	if lineText != "" && !strings.Contains(unifiedErr.Message, "(line:") {
		unifiedErr.Message = fmt.Sprintf("%s (line: %s)", unifiedErr.Message, lineText)
	}

	unifiedErr.WithPosition(m.PositionForGeneratedOffset(generatedOffset))
	return unifiedErr
}

// ComposePositions composes local generated->input positions onto prev input->source positions.
func ComposePositions(prev, local []int) []int {
	if len(local) == 0 {
		return nil
	}
	if len(prev) == 0 {
		return clonePositions(local)
	}
	out := make([]int, len(local))
	for i, pos := range local {
		out[i] = prev[ClampIndex(pos, len(prev))]
	}
	return out
}

// IdentityPositions returns an identity mapping of the given length.
func IdentityPositions(length int) []int {
	if length <= 0 {
		return nil
	}
	positions := make([]int, length)
	for i := range positions {
		positions[i] = i
	}
	return positions
}

func clonePositions(positions []int) []int {
	if len(positions) == 0 {
		return nil
	}
	cloned := make([]int, len(positions))
	copy(cloned, positions)
	return cloned
}

// ClampIndex clamps an index to the valid range for a sequence of length.
func ClampIndex(pos, length int) int {
	if length <= 0 {
		return 0
	}
	if pos < 0 {
		return 0
	}
	if pos >= length {
		return length - 1
	}
	return pos
}

func clampOffset(offset, length int) int {
	if offset < 0 {
		return 0
	}
	if offset > length {
		return length
	}
	return offset
}

func parseLineColPrefix(message string) (line int, col int, ok bool) {
	_, err := fmt.Sscanf(message, "%d:%d:", &line, &col)
	return line, col, err == nil
}

func stripLineColPrefix(message string) string {
	if idx := strings.Index(message, ": "); idx >= 0 {
		return message[idx+2:]
	}
	return message
}

func generatedLineColOffset(generated string, line, col int) int {
	if line <= 0 {
		line = 1
	}
	if col <= 0 {
		col = 1
	}
	offset := 0
	lines := strings.Split(generated, "\n")
	for i := 0; i < line-1 && i < len(lines); i++ {
		offset += len(lines[i]) + 1
	}
	offset += col - 1
	if offset >= len(generated) && len(generated) > 0 {
		offset = len(generated) - 1
	}
	if offset < 0 {
		offset = 0
	}
	return offset
}
