package evaluator

func collectionBuiltinSpecs() []BuiltinSpec {
	return []BuiltinSpec{
		specialBuiltinSpec("__filter", builtinCategoryArrays, exactArity(2), callBuiltinFilter, "array filter"),
		specialBuiltinSpec("__filter_selector", builtinCategoryArrays, exactArity(2), callBuiltinFilterSelector, "selector filter"),
		specialBuiltinSpec("__map", builtinCategoryArrays, exactArity(2), callBuiltinMap, "array map"),
		specialBuiltinSpec("__reduce", builtinCategoryArrays, exactArity(2), callBuiltinReduce, "array reduce"),
		specialBuiltinSpec("__groupBy", builtinCategoryArrays, exactArity(2), callBuiltinGroupBy, "group values"),
		specialBuiltinSpec("__flatMap", builtinCategoryArrays, exactArity(2), callBuiltinFlatMap, "flat map values"),
		specialBuiltinSpec("__toStream", builtinCategoryArrays, exactArity(1), callBuiltinToStream, "lazy stream conversion"),
		specialBuiltinSpec("__lazyMap", builtinCategoryArrays, exactArity(2), callBuiltinLazyMap, "lazy stream map"),
		specialBuiltinSpec("__lazyFilter", builtinCategoryArrays, exactArity(2), callBuiltinLazyFilter, "lazy stream filter"),
		specialBuiltinSpec("__lazyReduce", builtinCategoryArrays, exactArity(2), callBuiltinLazyReduce, "lazy stream reduce"),
		specialBuiltinSpec("maxBy", builtinCategoryArrays, exactArity(2), callBuiltinMaxBy, "maximum by selector"),
		specialBuiltinSpec("minBy", builtinCategoryArrays, exactArity(2), callBuiltinMinBy, "minimum by selector"),
		specialBuiltinSpec("orderBy", builtinCategoryArrays, exactArity(2), callBuiltinOrderBy, "order by selector"),
		specialBuiltinSpec("distinctBy", builtinCategoryArrays, exactArity(2), callBuiltinDistinctBy, "distinct by selector"),
		specialBuiltinSpec("filterObject", builtinCategoryObjects, exactArity(2), callBuiltinFilterObject, "object filter"),
		specialBuiltinSpec("groupBy", builtinCategoryArrays, exactArity(2), callBuiltinGroupBy, "group values"),
		specialBuiltinSpec("flatMap", builtinCategoryArrays, exactArity(2), callBuiltinFlatMap, "flat map values"),
		specialBuiltinSpec("mapObject", builtinCategoryObjects, exactArity(2), callBuiltinMapObject, "object map"),
		specialBuiltinSpec("pluck", builtinCategoryObjects, exactArity(2), callBuiltinPluck, "object pluck"),
		specialBuiltinSpec("__pluck", builtinCategoryObjects, exactArity(2), callBuiltinPluck, "object pluck"),
		specialBuiltinSpec("takeWhile", builtinCategoryArrays, exactArity(2), callBuiltinTakeWhile, "take while predicate matches"),
		specialBuiltinSpec("dropWhile", builtinCategoryArrays, exactArity(2), callBuiltinDropWhile, "drop while predicate matches"),
		specialBuiltinSpec("some", builtinCategoryArrays, exactArity(2), callBuiltinSome, "any item matches"),
		specialBuiltinSpec("every", builtinCategoryArrays, exactArity(2), callBuiltinEvery, "all items match"),
		specialBuiltinSpec("__updateExpr", builtinCategoryObjects, exactArity(2), callBuiltinUpdateExpr, "update expression"),
		regularBuiltinSpec("__concat", builtinCategoryArrays, variadicArity(2), callBuiltinConcat, "concatenate values"),
		regularBuiltinSpec("__remove", builtinCategoryArrays, exactArity(2), callBuiltinRemove, "remove values"),
		regularBuiltinSpec("sizeOf", builtinCategoryArrays, exactArity(1), callBuiltinSizeOf, "collection size"),
		regularBuiltinSpec("isEmpty", builtinCategoryArrays, exactArity(1), callBuiltinIsEmpty, "empty value check"),
		regularBuiltinSpec("flatten", builtinCategoryArrays, exactArity(1), callBuiltinFlatten, "flatten nested arrays"),
		regularBuiltinSpec("unique", builtinCategoryArrays, exactArity(1), callBuiltinUnique, "unique array values"),
		regularBuiltinSpec("reverse", builtinCategoryArrays, exactArity(1), callBuiltinReverse, "reverse array"),
		regularBuiltinSpec("sort", builtinCategoryArrays, exactArity(1), callBuiltinSort, "sort array"),
		regularBuiltinSpec("join", builtinCategoryArrays, exactArity(2), callBuiltinJoin, "join array values"),
		regularBuiltinSpec("keys", builtinCategoryObjects, exactArity(1), callBuiltinKeys, "object keys"),
		regularBuiltinSpec("values", builtinCategoryObjects, exactArity(1), callBuiltinValues, "object values"),
		regularBuiltinSpec("merge", builtinCategoryObjects, variadicArity(1), callBuiltinMerge, "merge objects"),
		regularBuiltinSpec("__with_attrs", builtinCategoryObjects, exactArity(2), callBuiltinWithAttrs, "attach XML attributes"),
		regularBuiltinSpec("__update", builtinCategoryObjects, exactArity(2), callBuiltinUpdate, "object update"),
		regularBuiltinSpec("__deep", builtinCategoryObjects, exactArity(2), callBuiltinDeep, "recursive descent"),
		regularBuiltinSpec("__objvalues", builtinCategoryObjects, exactArity(1), callBuiltinObjectValues, "object values"),
		regularBuiltinSpec("__multival", builtinCategoryObjects, variadicArity(0), callBuiltinMultival, "XML multi-value wrapper"),
		regularBuiltinSpec("__metadata", builtinCategoryObjects, exactArity(2), callBuiltinMetadata, "metadata selector"),
		regularBuiltinSpec("objectToArray", builtinCategoryObjects, exactArity(1), callBuiltinObjectToArray, "object entries as array"),
		regularBuiltinSpec("arrayToObject", builtinCategoryObjects, exactArity(1), callBuiltinArrayToObject, "entries array as object"),
		regularBuiltinSpec("entriesOf", builtinCategoryObjects, exactArity(1), callBuiltinEntriesOf, "object entries"),
		regularBuiltinSpec("keysOf", builtinCategoryObjects, exactArity(1), callBuiltinKeysOf, "object keys"),
		regularBuiltinSpec("valuesOf", builtinCategoryObjects, exactArity(1), callBuiltinValuesOf, "object values"),
		regularBuiltinSpec("namesOf", builtinCategoryObjects, exactArity(1), callBuiltinNamesOf, "object names"),
		regularBuiltinSpec("zip", builtinCategoryArrays, exactArity(2), callBuiltinZip, "zip arrays"),
		regularBuiltinSpec("unzip", builtinCategoryArrays, exactArity(1), callBuiltinUnzip, "unzip pairs"),
		regularBuiltinSpec("range", builtinCategoryArrays, exactArity(1), callBuiltinRange, "zero-based range"),
		regularBuiltinSpec("distinct", builtinCategoryArrays, exactArity(1), callBuiltinDistinct, "distinct values"),
		regularBuiltinSpec("__range", builtinCategoryArrays, exactArity(1), callBuiltinRange, "zero-based range"),
		regularBuiltinSpec("with", builtinCategoryObjects, exactArity(2), callBuiltinWith, "replace selected value"),
		regularBuiltinSpec("xsiType", builtinCategoryObjects, exactArity(1), callBuiltinXsiType, "XML xsi:type object"),
		regularBuiltinSpec("slice", builtinCategoryArrays, exactArity(3), callBuiltinSlice, "slice array or string"),
		regularBuiltinSpec("prepend", builtinCategoryArrays, exactArity(2), callBuiltinPrepend, "prepend value"),
		regularBuiltinSpec("append", builtinCategoryArrays, exactArity(2), callBuiltinAppend, "append value"),
		regularBuiltinSpec("safe", builtinCategoryObjects, exactArity(2), callBuiltinSafeAccess, "safe access"),
		regularBuiltinSpec("first", builtinCategoryArrays, exactArity(1), callBuiltinFirst, "first array value"),
		regularBuiltinSpec("last", builtinCategoryArrays, exactArity(1), callBuiltinLast, "last array value"),
		regularBuiltinSpec("take", builtinCategoryArrays, exactArity(2), callBuiltinTake, "take array values"),
		regularBuiltinSpec("drop", builtinCategoryArrays, exactArity(2), callBuiltinDrop, "drop array values"),
	}
}
