package evaluator

func stringBuiltinSpecs() []BuiltinSpec {
	return []BuiltinSpec{
		regularBuiltinSpec("trim", builtinCategoryStrings, exactArity(1), callBuiltinTrim, "trim whitespace"),
		regularBuiltinSpec("length", builtinCategoryStrings, exactArity(1), callBuiltinLength, "value length"),
		regularBuiltinSpec("repeat", builtinCategoryStrings, exactArity(2), callBuiltinRepeat, "repeat string"),
		regularBuiltinSpec("split", builtinCategoryStrings, exactArity(2), callBuiltinSplit, "split string"),
		regularBuiltinSpec("substring", builtinCategoryStrings, rangeArity(2, 3), callBuiltinSubstring, "substring"),
		regularBuiltinSpec("charAt", builtinCategoryStrings, exactArity(2), callBuiltinCharAt, "character at index"),
		regularBuiltinSpec("charCodeAt", builtinCategoryStrings, exactArity(2), callBuiltinCharCodeAt, "character code at index"),
		regularBuiltinSpec("fromCharCode", builtinCategoryStrings, exactArity(1), callBuiltinFromCharCode, "string from character code"),
		regularBuiltinSpec("indexOf", builtinCategoryStrings, exactArity(2), callBuiltinIndexOf, "first index of value"),
		regularBuiltinSpec("lastIndexOf", builtinCategoryStrings, exactArity(2), callBuiltinLastIndexOf, "last index of value"),
		regularBuiltinSpec("appendIfMissing", builtinCategoryStrings, exactArity(2), callBuiltinAppendIfMissing, "append missing suffix"),
		regularBuiltinSpec("prependIfMissing", builtinCategoryStrings, exactArity(2), callBuiltinPrependIfMissing, "prepend missing prefix"),
		regularBuiltinSpec("toUpper", builtinCategoryStrings, exactArity(1), callBuiltinToUpper, "uppercase string"),
		regularBuiltinSpec("toLower", builtinCategoryStrings, exactArity(1), callBuiltinToLower, "lowercase string"),
		regularBuiltinSpec("toBase64", builtinCategoryStrings, exactArity(1), callBuiltinToBase64, "base64 encode"),
		regularBuiltinSpec("fromBase64", builtinCategoryStrings, exactArity(1), callBuiltinFromBase64, "base64 decode"),
		regularBuiltinSpec("hash", builtinCategoryStrings, exactArity(2), callBuiltinHash, "hash string"),
		regularBuiltinSpec("toHex", builtinCategoryStrings, exactArity(1), callBuiltinToHex, "hex encode"),
		regularBuiltinSpec("fromHex", builtinCategoryStrings, exactArity(1), callBuiltinFromHex, "hex decode"),
		regularBuiltinSpec("upper", builtinCategoryStrings, exactArity(1), callBuiltinUpper, "uppercase string"),
		regularBuiltinSpec("lower", builtinCategoryStrings, exactArity(1), callBuiltinLower, "lowercase string"),
		regularBuiltinSpec("capitalize", builtinCategoryStrings, exactArity(1), callBuiltinCapitalize, "capitalize string"),
		regularBuiltinSpec("camelize", builtinCategoryStrings, exactArity(1), callBuiltinCamelize, "camel-case string"),
		regularBuiltinSpec("dasherize", builtinCategoryStrings, exactArity(1), callBuiltinDasherize, "dash-case string"),
		regularBuiltinSpec("underscore", builtinCategoryStrings, exactArity(1), callBuiltinUnderscore, "underscore string"),
		regularBuiltinSpec("pluralize", builtinCategoryStrings, exactArity(1), callBuiltinPluralize, "pluralize string"),
		regularBuiltinSpec("singularize", builtinCategoryStrings, exactArity(1), callBuiltinSingularize, "singularize string"),
		regularBuiltinSpec("ordinalize", builtinCategoryStrings, exactArity(1), callBuiltinOrdinalize, "ordinalize number"),
		regularBuiltinSpec("leftPad", builtinCategoryStrings, exactArity(3), callBuiltinLeftPad, "left pad string"),
		regularBuiltinSpec("rightPad", builtinCategoryStrings, exactArity(3), callBuiltinRightPad, "right pad string"),
		regularBuiltinSpec("startsWith", builtinCategoryStrings, exactArity(2), callBuiltinStartsWith, "starts with"),
		regularBuiltinSpec("endsWith", builtinCategoryStrings, exactArity(2), callBuiltinEndsWith, "ends with"),
		regularBuiltinSpec("contains", builtinCategoryStrings, exactArity(2), callBuiltinContains, "contains value"),
		regularBuiltinSpec("replace", builtinCategoryStrings, exactArity(3), callBuiltinReplace, "replace text"),
		regularBuiltinSpec("regex", builtinCategoryStrings, rangeArity(1, 2), callBuiltinRegex, "compile regex"),
		regularBuiltinSpec("find", builtinCategoryStrings, rangeArity(2, 3), callBuiltinFind, "find value"),
		regularBuiltinSpec("match", builtinCategoryStrings, rangeArity(2, 3), callBuiltinMatch, "regex match"),
		regularBuiltinSpec("matches", builtinCategoryStrings, rangeArity(2, 3), callBuiltinMatches, "regex matches"),
		regularBuiltinSpec("scan", builtinCategoryStrings, rangeArity(2, 3), callBuiltinScan, "regex scan"),
		regularBuiltinSpec("isBlank", builtinCategoryStrings, exactArity(1), callBuiltinIsBlank, "blank string check"),
		regularBuiltinSpec("joinBy", builtinCategoryStrings, exactArity(2), callBuiltinJoinBy, "join strings"),
		regularBuiltinSpec("splitBy", builtinCategoryStrings, exactArity(2), callBuiltinSplitBy, "split string"),
	}
}
